/*
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
