/*
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("x/mvmn/permock/dsl/parser/antlr/internal/InternalDsl.tokens");
	}
}
