/**
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link x.mvmn.permock.dsl.dsl.Constant#getStrVal <em>Str Val</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.Constant#getIntVal <em>Int Val</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.Constant#getFloatVal <em>Float Val</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.Constant#getBoolVal <em>Bool Val</em>}</li>
 * </ul>
 *
 * @see x.mvmn.permock.dsl.dsl.DslPackage#getConstant()
 * @model
 * @generated
 */
public interface Constant extends EObject
{
  /**
   * Returns the value of the '<em><b>Str Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Str Val</em>' attribute.
   * @see #setStrVal(String)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getConstant_StrVal()
   * @model
   * @generated
   */
  String getStrVal();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.Constant#getStrVal <em>Str Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Str Val</em>' attribute.
   * @see #getStrVal()
   * @generated
   */
  void setStrVal(String value);

  /**
   * Returns the value of the '<em><b>Int Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Val</em>' attribute.
   * @see #setIntVal(Long)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getConstant_IntVal()
   * @model
   * @generated
   */
  Long getIntVal();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.Constant#getIntVal <em>Int Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Val</em>' attribute.
   * @see #getIntVal()
   * @generated
   */
  void setIntVal(Long value);

  /**
   * Returns the value of the '<em><b>Float Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Float Val</em>' attribute.
   * @see #setFloatVal(Double)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getConstant_FloatVal()
   * @model
   * @generated
   */
  Double getFloatVal();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.Constant#getFloatVal <em>Float Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Float Val</em>' attribute.
   * @see #getFloatVal()
   * @generated
   */
  void setFloatVal(Double value);

  /**
   * Returns the value of the '<em><b>Bool Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool Val</em>' attribute.
   * @see #setBoolVal(Boolean)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getConstant_BoolVal()
   * @model
   * @generated
   */
  Boolean getBoolVal();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.Constant#getBoolVal <em>Bool Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool Val</em>' attribute.
   * @see #getBoolVal()
   * @generated
   */
  void setBoolVal(Boolean value);

} // Constant
