/**
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see x.mvmn.permock.dsl.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mvmn.x/permock/dsl/Dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslPackage eINSTANCE = x.mvmn.permock.dsl.dsl.impl.DslPackageImpl.init();

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.RuleImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getRule()
   * @generated
   */
  int RULE = 0;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CONDITIONS = 0;

  /**
   * The feature id for the '<em><b>Proxy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__PROXY = 1;

  /**
   * The feature id for the '<em><b>Response</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__RESPONSE = 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.ProxyConfImpl <em>Proxy Conf</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.ProxyConfImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getProxyConf()
   * @generated
   */
  int PROXY_CONF = 1;

  /**
   * The feature id for the '<em><b>Proxy Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROXY_CONF__PROXY_URL = 0;

  /**
   * The number of structural features of the '<em>Proxy Conf</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROXY_CONF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.ResponseConfImpl <em>Response Conf</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.ResponseConfImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getResponseConf()
   * @generated
   */
  int RESPONSE_CONF = 2;

  /**
   * The feature id for the '<em><b>Http Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE_CONF__HTTP_STATUS = 0;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE_CONF__CONTENT = 1;

  /**
   * The feature id for the '<em><b>Headers</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE_CONF__HEADERS = 2;

  /**
   * The number of structural features of the '<em>Response Conf</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE_CONF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.HeadersImpl <em>Headers</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.HeadersImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getHeaders()
   * @generated
   */
  int HEADERS = 3;

  /**
   * The feature id for the '<em><b>Headers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADERS__HEADERS = 0;

  /**
   * The number of structural features of the '<em>Headers</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADERS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.HeaderImpl <em>Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.HeaderImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getHeader()
   * @generated
   */
  int HEADER = 4;

  /**
   * The feature id for the '<em><b>Header Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__HEADER_NAME = 0;

  /**
   * The feature id for the '<em><b>Header Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__HEADER_VALUE = 1;

  /**
   * The number of structural features of the '<em>Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.ConditionImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 5;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__EXPRESSION = 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CONDITION = 1;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.ExpressionImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.OperandImpl <em>Operand</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.OperandImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getOperand()
   * @generated
   */
  int OPERAND = 7;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERAND__REF = 0;

  /**
   * The feature id for the '<em><b>Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERAND__CONST = 1;

  /**
   * The feature id for the '<em><b>List Element Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERAND__LIST_ELEMENT_REF = 2;

  /**
   * The number of structural features of the '<em>Operand</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERAND_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.ListFunctionImpl <em>List Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.ListFunctionImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getListFunction()
   * @generated
   */
  int LIST_FUNCTION = 8;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FUNCTION__OP = 0;

  /**
   * The feature id for the '<em><b>Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FUNCTION__ALIAS = 1;

  /**
   * The feature id for the '<em><b>Separator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FUNCTION__SEPARATOR = 2;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FUNCTION__CONDITION = 3;

  /**
   * The number of structural features of the '<em>List Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FUNCTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.ListElementAliasImpl <em>List Element Alias</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.ListElementAliasImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getListElementAlias()
   * @generated
   */
  int LIST_ELEMENT_ALIAS = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_ELEMENT_ALIAS__NAME = 0;

  /**
   * The number of structural features of the '<em>List Element Alias</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_ELEMENT_ALIAS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.ReferenceImpl <em>Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.ReferenceImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getReference()
   * @generated
   */
  int REFERENCE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__NAME = 0;

  /**
   * The feature id for the '<em><b>Prop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__PROP = 1;

  /**
   * The number of structural features of the '<em>Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.ListElementReferenceImpl <em>List Element Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.ListElementReferenceImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getListElementReference()
   * @generated
   */
  int LIST_ELEMENT_REFERENCE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_ELEMENT_REFERENCE__NAME = 0;

  /**
   * The feature id for the '<em><b>Prop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_ELEMENT_REFERENCE__PROP = 1;

  /**
   * The number of structural features of the '<em>List Element Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_ELEMENT_REFERENCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.CollectionAccessImpl <em>Collection Access</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.CollectionAccessImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getCollectionAccess()
   * @generated
   */
  int COLLECTION_ACCESS = 12;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_ACCESS__KEY = 0;

  /**
   * The feature id for the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_ACCESS__INDEX = 1;

  /**
   * The number of structural features of the '<em>Collection Access</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_ACCESS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.PropertyAccessImpl <em>Property Access</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.PropertyAccessImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getPropertyAccess()
   * @generated
   */
  int PROPERTY_ACCESS = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_ACCESS__NAME = 0;

  /**
   * The number of structural features of the '<em>Property Access</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_ACCESS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.FunctionCallImpl <em>Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.FunctionCallImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getFunctionCall()
   * @generated
   */
  int FUNCTION_CALL = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__NAME = 0;

  /**
   * The feature id for the '<em><b>Function Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__FUNCTION_PARAMETERS = 1;

  /**
   * The number of structural features of the '<em>Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.PropertyRefImpl <em>Property Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.PropertyRefImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getPropertyRef()
   * @generated
   */
  int PROPERTY_REF = 15;

  /**
   * The feature id for the '<em><b>Prop Access</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_REF__PROP_ACCESS = 0;

  /**
   * The feature id for the '<em><b>Function Call</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_REF__FUNCTION_CALL = 1;

  /**
   * The feature id for the '<em><b>Collection Access</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_REF__COLLECTION_ACCESS = 2;

  /**
   * The feature id for the '<em><b>List Func</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_REF__LIST_FUNC = 3;

  /**
   * The feature id for the '<em><b>Sub Propery</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_REF__SUB_PROPERY = 4;

  /**
   * The number of structural features of the '<em>Property Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_REF_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.ConstantImpl <em>Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.ConstantImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getConstant()
   * @generated
   */
  int CONSTANT = 16;

  /**
   * The feature id for the '<em><b>Str Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__STR_VAL = 0;

  /**
   * The feature id for the '<em><b>Int Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__INT_VAL = 1;

  /**
   * The feature id for the '<em><b>Float Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__FLOAT_VAL = 2;

  /**
   * The feature id for the '<em><b>Bool Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__BOOL_VAL = 3;

  /**
   * The number of structural features of the '<em>Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.EntityImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 0;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.OrConditionImpl <em>Or Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.OrConditionImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getOrCondition()
   * @generated
   */
  int OR_CONDITION = 18;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CONDITION__EXPRESSION = CONDITION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CONDITION__CONDITION = CONDITION__CONDITION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CONDITION__LEFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CONDITION__RIGHT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.AndConditionImpl <em>And Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.AndConditionImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getAndCondition()
   * @generated
   */
  int AND_CONDITION = 19;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CONDITION__EXPRESSION = CONDITION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CONDITION__CONDITION = CONDITION__CONDITION;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CONDITION__LEFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CONDITION__RIGHT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.impl.NegationImpl <em>Negation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.impl.NegationImpl
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getNegation()
   * @generated
   */
  int NEGATION = 20;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATION__EXPRESSION = CONDITION__EXPRESSION;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATION__CONDITION = CONDITION__CONDITION;

  /**
   * The feature id for the '<em><b>Negated</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATION__NEGATED = CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Negation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.Operator <em>Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.Operator
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getOperator()
   * @generated
   */
  int OPERATOR = 21;

  /**
   * The meta object id for the '{@link x.mvmn.permock.dsl.dsl.ListOperation <em>List Operation</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see x.mvmn.permock.dsl.dsl.ListOperation
   * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getListOperation()
   * @generated
   */
  int LIST_OPERATION = 22;


  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see x.mvmn.permock.dsl.dsl.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Rule#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conditions</em>'.
   * @see x.mvmn.permock.dsl.dsl.Rule#getConditions()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Conditions();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Rule#getProxy <em>Proxy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Proxy</em>'.
   * @see x.mvmn.permock.dsl.dsl.Rule#getProxy()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Proxy();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Rule#getResponse <em>Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Response</em>'.
   * @see x.mvmn.permock.dsl.dsl.Rule#getResponse()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Response();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.ProxyConf <em>Proxy Conf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Proxy Conf</em>'.
   * @see x.mvmn.permock.dsl.dsl.ProxyConf
   * @generated
   */
  EClass getProxyConf();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.ProxyConf#getProxyUrl <em>Proxy Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Proxy Url</em>'.
   * @see x.mvmn.permock.dsl.dsl.ProxyConf#getProxyUrl()
   * @see #getProxyConf()
   * @generated
   */
  EAttribute getProxyConf_ProxyUrl();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.ResponseConf <em>Response Conf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Response Conf</em>'.
   * @see x.mvmn.permock.dsl.dsl.ResponseConf
   * @generated
   */
  EClass getResponseConf();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.ResponseConf#getHttpStatus <em>Http Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Http Status</em>'.
   * @see x.mvmn.permock.dsl.dsl.ResponseConf#getHttpStatus()
   * @see #getResponseConf()
   * @generated
   */
  EAttribute getResponseConf_HttpStatus();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.ResponseConf#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Content</em>'.
   * @see x.mvmn.permock.dsl.dsl.ResponseConf#getContent()
   * @see #getResponseConf()
   * @generated
   */
  EAttribute getResponseConf_Content();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.ResponseConf#getHeaders <em>Headers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Headers</em>'.
   * @see x.mvmn.permock.dsl.dsl.ResponseConf#getHeaders()
   * @see #getResponseConf()
   * @generated
   */
  EReference getResponseConf_Headers();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.Headers <em>Headers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Headers</em>'.
   * @see x.mvmn.permock.dsl.dsl.Headers
   * @generated
   */
  EClass getHeaders();

  /**
   * Returns the meta object for the containment reference list '{@link x.mvmn.permock.dsl.dsl.Headers#getHeaders <em>Headers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Headers</em>'.
   * @see x.mvmn.permock.dsl.dsl.Headers#getHeaders()
   * @see #getHeaders()
   * @generated
   */
  EReference getHeaders_Headers();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.Header <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Header</em>'.
   * @see x.mvmn.permock.dsl.dsl.Header
   * @generated
   */
  EClass getHeader();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.Header#getHeaderName <em>Header Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Header Name</em>'.
   * @see x.mvmn.permock.dsl.dsl.Header#getHeaderName()
   * @see #getHeader()
   * @generated
   */
  EAttribute getHeader_HeaderName();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.Header#getHeaderValue <em>Header Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Header Value</em>'.
   * @see x.mvmn.permock.dsl.dsl.Header#getHeaderValue()
   * @see #getHeader()
   * @generated
   */
  EAttribute getHeader_HeaderValue();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see x.mvmn.permock.dsl.dsl.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Condition#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see x.mvmn.permock.dsl.dsl.Condition#getExpression()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Expression();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Condition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see x.mvmn.permock.dsl.dsl.Condition#getCondition()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Condition();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see x.mvmn.permock.dsl.dsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see x.mvmn.permock.dsl.dsl.Expression#getLeft()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Left();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.Expression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see x.mvmn.permock.dsl.dsl.Expression#getOp()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see x.mvmn.permock.dsl.dsl.Expression#getRight()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Right();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.Operand <em>Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operand</em>'.
   * @see x.mvmn.permock.dsl.dsl.Operand
   * @generated
   */
  EClass getOperand();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Operand#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see x.mvmn.permock.dsl.dsl.Operand#getRef()
   * @see #getOperand()
   * @generated
   */
  EReference getOperand_Ref();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Operand#getConst <em>Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Const</em>'.
   * @see x.mvmn.permock.dsl.dsl.Operand#getConst()
   * @see #getOperand()
   * @generated
   */
  EReference getOperand_Const();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Operand#getListElementRef <em>List Element Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List Element Ref</em>'.
   * @see x.mvmn.permock.dsl.dsl.Operand#getListElementRef()
   * @see #getOperand()
   * @generated
   */
  EReference getOperand_ListElementRef();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.ListFunction <em>List Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Function</em>'.
   * @see x.mvmn.permock.dsl.dsl.ListFunction
   * @generated
   */
  EClass getListFunction();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.ListFunction#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see x.mvmn.permock.dsl.dsl.ListFunction#getOp()
   * @see #getListFunction()
   * @generated
   */
  EAttribute getListFunction_Op();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.ListFunction#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alias</em>'.
   * @see x.mvmn.permock.dsl.dsl.ListFunction#getAlias()
   * @see #getListFunction()
   * @generated
   */
  EReference getListFunction_Alias();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.ListFunction#getSeparator <em>Separator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Separator</em>'.
   * @see x.mvmn.permock.dsl.dsl.ListFunction#getSeparator()
   * @see #getListFunction()
   * @generated
   */
  EAttribute getListFunction_Separator();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.ListFunction#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see x.mvmn.permock.dsl.dsl.ListFunction#getCondition()
   * @see #getListFunction()
   * @generated
   */
  EReference getListFunction_Condition();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.ListElementAlias <em>List Element Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Element Alias</em>'.
   * @see x.mvmn.permock.dsl.dsl.ListElementAlias
   * @generated
   */
  EClass getListElementAlias();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.ListElementAlias#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see x.mvmn.permock.dsl.dsl.ListElementAlias#getName()
   * @see #getListElementAlias()
   * @generated
   */
  EAttribute getListElementAlias_Name();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.Reference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference</em>'.
   * @see x.mvmn.permock.dsl.dsl.Reference
   * @generated
   */
  EClass getReference();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Reference#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see x.mvmn.permock.dsl.dsl.Reference#getName()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Name();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Reference#getProp <em>Prop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prop</em>'.
   * @see x.mvmn.permock.dsl.dsl.Reference#getProp()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Prop();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.ListElementReference <em>List Element Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Element Reference</em>'.
   * @see x.mvmn.permock.dsl.dsl.ListElementReference
   * @generated
   */
  EClass getListElementReference();

  /**
   * Returns the meta object for the reference '{@link x.mvmn.permock.dsl.dsl.ListElementReference#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see x.mvmn.permock.dsl.dsl.ListElementReference#getName()
   * @see #getListElementReference()
   * @generated
   */
  EReference getListElementReference_Name();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.ListElementReference#getProp <em>Prop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prop</em>'.
   * @see x.mvmn.permock.dsl.dsl.ListElementReference#getProp()
   * @see #getListElementReference()
   * @generated
   */
  EReference getListElementReference_Prop();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.CollectionAccess <em>Collection Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Collection Access</em>'.
   * @see x.mvmn.permock.dsl.dsl.CollectionAccess
   * @generated
   */
  EClass getCollectionAccess();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.CollectionAccess#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see x.mvmn.permock.dsl.dsl.CollectionAccess#getKey()
   * @see #getCollectionAccess()
   * @generated
   */
  EAttribute getCollectionAccess_Key();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.CollectionAccess#getIndex <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Index</em>'.
   * @see x.mvmn.permock.dsl.dsl.CollectionAccess#getIndex()
   * @see #getCollectionAccess()
   * @generated
   */
  EAttribute getCollectionAccess_Index();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.PropertyAccess <em>Property Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Access</em>'.
   * @see x.mvmn.permock.dsl.dsl.PropertyAccess
   * @generated
   */
  EClass getPropertyAccess();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.PropertyAccess#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see x.mvmn.permock.dsl.dsl.PropertyAccess#getName()
   * @see #getPropertyAccess()
   * @generated
   */
  EAttribute getPropertyAccess_Name();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.FunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call</em>'.
   * @see x.mvmn.permock.dsl.dsl.FunctionCall
   * @generated
   */
  EClass getFunctionCall();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.FunctionCall#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see x.mvmn.permock.dsl.dsl.FunctionCall#getName()
   * @see #getFunctionCall()
   * @generated
   */
  EAttribute getFunctionCall_Name();

  /**
   * Returns the meta object for the containment reference list '{@link x.mvmn.permock.dsl.dsl.FunctionCall#getFunctionParameters <em>Function Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Function Parameters</em>'.
   * @see x.mvmn.permock.dsl.dsl.FunctionCall#getFunctionParameters()
   * @see #getFunctionCall()
   * @generated
   */
  EReference getFunctionCall_FunctionParameters();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.PropertyRef <em>Property Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Ref</em>'.
   * @see x.mvmn.permock.dsl.dsl.PropertyRef
   * @generated
   */
  EClass getPropertyRef();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.PropertyRef#getPropAccess <em>Prop Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prop Access</em>'.
   * @see x.mvmn.permock.dsl.dsl.PropertyRef#getPropAccess()
   * @see #getPropertyRef()
   * @generated
   */
  EReference getPropertyRef_PropAccess();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.PropertyRef#getFunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Function Call</em>'.
   * @see x.mvmn.permock.dsl.dsl.PropertyRef#getFunctionCall()
   * @see #getPropertyRef()
   * @generated
   */
  EReference getPropertyRef_FunctionCall();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.PropertyRef#getCollectionAccess <em>Collection Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Collection Access</em>'.
   * @see x.mvmn.permock.dsl.dsl.PropertyRef#getCollectionAccess()
   * @see #getPropertyRef()
   * @generated
   */
  EReference getPropertyRef_CollectionAccess();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.PropertyRef#getListFunc <em>List Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List Func</em>'.
   * @see x.mvmn.permock.dsl.dsl.PropertyRef#getListFunc()
   * @see #getPropertyRef()
   * @generated
   */
  EReference getPropertyRef_ListFunc();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.PropertyRef#getSubPropery <em>Sub Propery</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sub Propery</em>'.
   * @see x.mvmn.permock.dsl.dsl.PropertyRef#getSubPropery()
   * @see #getPropertyRef()
   * @generated
   */
  EReference getPropertyRef_SubPropery();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.Constant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constant</em>'.
   * @see x.mvmn.permock.dsl.dsl.Constant
   * @generated
   */
  EClass getConstant();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.Constant#getStrVal <em>Str Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str Val</em>'.
   * @see x.mvmn.permock.dsl.dsl.Constant#getStrVal()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_StrVal();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.Constant#getIntVal <em>Int Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int Val</em>'.
   * @see x.mvmn.permock.dsl.dsl.Constant#getIntVal()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_IntVal();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.Constant#getFloatVal <em>Float Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Float Val</em>'.
   * @see x.mvmn.permock.dsl.dsl.Constant#getFloatVal()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_FloatVal();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.Constant#getBoolVal <em>Bool Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool Val</em>'.
   * @see x.mvmn.permock.dsl.dsl.Constant#getBoolVal()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_BoolVal();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see x.mvmn.permock.dsl.dsl.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link x.mvmn.permock.dsl.dsl.Entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see x.mvmn.permock.dsl.dsl.Entity#getName()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Name();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.OrCondition <em>Or Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Condition</em>'.
   * @see x.mvmn.permock.dsl.dsl.OrCondition
   * @generated
   */
  EClass getOrCondition();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.OrCondition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see x.mvmn.permock.dsl.dsl.OrCondition#getLeft()
   * @see #getOrCondition()
   * @generated
   */
  EReference getOrCondition_Left();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.OrCondition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see x.mvmn.permock.dsl.dsl.OrCondition#getRight()
   * @see #getOrCondition()
   * @generated
   */
  EReference getOrCondition_Right();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.AndCondition <em>And Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Condition</em>'.
   * @see x.mvmn.permock.dsl.dsl.AndCondition
   * @generated
   */
  EClass getAndCondition();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.AndCondition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see x.mvmn.permock.dsl.dsl.AndCondition#getLeft()
   * @see #getAndCondition()
   * @generated
   */
  EReference getAndCondition_Left();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.AndCondition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see x.mvmn.permock.dsl.dsl.AndCondition#getRight()
   * @see #getAndCondition()
   * @generated
   */
  EReference getAndCondition_Right();

  /**
   * Returns the meta object for class '{@link x.mvmn.permock.dsl.dsl.Negation <em>Negation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Negation</em>'.
   * @see x.mvmn.permock.dsl.dsl.Negation
   * @generated
   */
  EClass getNegation();

  /**
   * Returns the meta object for the containment reference '{@link x.mvmn.permock.dsl.dsl.Negation#getNegated <em>Negated</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Negated</em>'.
   * @see x.mvmn.permock.dsl.dsl.Negation#getNegated()
   * @see #getNegation()
   * @generated
   */
  EReference getNegation_Negated();

  /**
   * Returns the meta object for enum '{@link x.mvmn.permock.dsl.dsl.Operator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operator</em>'.
   * @see x.mvmn.permock.dsl.dsl.Operator
   * @generated
   */
  EEnum getOperator();

  /**
   * Returns the meta object for enum '{@link x.mvmn.permock.dsl.dsl.ListOperation <em>List Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>List Operation</em>'.
   * @see x.mvmn.permock.dsl.dsl.ListOperation
   * @generated
   */
  EEnum getListOperation();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslFactory getDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.RuleImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__CONDITIONS = eINSTANCE.getRule_Conditions();

    /**
     * The meta object literal for the '<em><b>Proxy</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__PROXY = eINSTANCE.getRule_Proxy();

    /**
     * The meta object literal for the '<em><b>Response</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__RESPONSE = eINSTANCE.getRule_Response();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.ProxyConfImpl <em>Proxy Conf</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.ProxyConfImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getProxyConf()
     * @generated
     */
    EClass PROXY_CONF = eINSTANCE.getProxyConf();

    /**
     * The meta object literal for the '<em><b>Proxy Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROXY_CONF__PROXY_URL = eINSTANCE.getProxyConf_ProxyUrl();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.ResponseConfImpl <em>Response Conf</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.ResponseConfImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getResponseConf()
     * @generated
     */
    EClass RESPONSE_CONF = eINSTANCE.getResponseConf();

    /**
     * The meta object literal for the '<em><b>Http Status</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESPONSE_CONF__HTTP_STATUS = eINSTANCE.getResponseConf_HttpStatus();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESPONSE_CONF__CONTENT = eINSTANCE.getResponseConf_Content();

    /**
     * The meta object literal for the '<em><b>Headers</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESPONSE_CONF__HEADERS = eINSTANCE.getResponseConf_Headers();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.HeadersImpl <em>Headers</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.HeadersImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getHeaders()
     * @generated
     */
    EClass HEADERS = eINSTANCE.getHeaders();

    /**
     * The meta object literal for the '<em><b>Headers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEADERS__HEADERS = eINSTANCE.getHeaders_Headers();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.HeaderImpl <em>Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.HeaderImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getHeader()
     * @generated
     */
    EClass HEADER = eINSTANCE.getHeader();

    /**
     * The meta object literal for the '<em><b>Header Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEADER__HEADER_NAME = eINSTANCE.getHeader_HeaderName();

    /**
     * The meta object literal for the '<em><b>Header Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEADER__HEADER_VALUE = eINSTANCE.getHeader_HeaderValue();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.ConditionImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__EXPRESSION = eINSTANCE.getCondition_Expression();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__CONDITION = eINSTANCE.getCondition_Condition();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.ExpressionImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__LEFT = eINSTANCE.getExpression_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__OP = eINSTANCE.getExpression_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__RIGHT = eINSTANCE.getExpression_Right();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.OperandImpl <em>Operand</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.OperandImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getOperand()
     * @generated
     */
    EClass OPERAND = eINSTANCE.getOperand();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERAND__REF = eINSTANCE.getOperand_Ref();

    /**
     * The meta object literal for the '<em><b>Const</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERAND__CONST = eINSTANCE.getOperand_Const();

    /**
     * The meta object literal for the '<em><b>List Element Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERAND__LIST_ELEMENT_REF = eINSTANCE.getOperand_ListElementRef();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.ListFunctionImpl <em>List Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.ListFunctionImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getListFunction()
     * @generated
     */
    EClass LIST_FUNCTION = eINSTANCE.getListFunction();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIST_FUNCTION__OP = eINSTANCE.getListFunction_Op();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_FUNCTION__ALIAS = eINSTANCE.getListFunction_Alias();

    /**
     * The meta object literal for the '<em><b>Separator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIST_FUNCTION__SEPARATOR = eINSTANCE.getListFunction_Separator();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_FUNCTION__CONDITION = eINSTANCE.getListFunction_Condition();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.ListElementAliasImpl <em>List Element Alias</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.ListElementAliasImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getListElementAlias()
     * @generated
     */
    EClass LIST_ELEMENT_ALIAS = eINSTANCE.getListElementAlias();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIST_ELEMENT_ALIAS__NAME = eINSTANCE.getListElementAlias_Name();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.ReferenceImpl <em>Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.ReferenceImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getReference()
     * @generated
     */
    EClass REFERENCE = eINSTANCE.getReference();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__NAME = eINSTANCE.getReference_Name();

    /**
     * The meta object literal for the '<em><b>Prop</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__PROP = eINSTANCE.getReference_Prop();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.ListElementReferenceImpl <em>List Element Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.ListElementReferenceImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getListElementReference()
     * @generated
     */
    EClass LIST_ELEMENT_REFERENCE = eINSTANCE.getListElementReference();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_ELEMENT_REFERENCE__NAME = eINSTANCE.getListElementReference_Name();

    /**
     * The meta object literal for the '<em><b>Prop</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_ELEMENT_REFERENCE__PROP = eINSTANCE.getListElementReference_Prop();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.CollectionAccessImpl <em>Collection Access</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.CollectionAccessImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getCollectionAccess()
     * @generated
     */
    EClass COLLECTION_ACCESS = eINSTANCE.getCollectionAccess();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION_ACCESS__KEY = eINSTANCE.getCollectionAccess_Key();

    /**
     * The meta object literal for the '<em><b>Index</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLLECTION_ACCESS__INDEX = eINSTANCE.getCollectionAccess_Index();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.PropertyAccessImpl <em>Property Access</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.PropertyAccessImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getPropertyAccess()
     * @generated
     */
    EClass PROPERTY_ACCESS = eINSTANCE.getPropertyAccess();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_ACCESS__NAME = eINSTANCE.getPropertyAccess_Name();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.FunctionCallImpl <em>Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.FunctionCallImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getFunctionCall()
     * @generated
     */
    EClass FUNCTION_CALL = eINSTANCE.getFunctionCall();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION_CALL__NAME = eINSTANCE.getFunctionCall_Name();

    /**
     * The meta object literal for the '<em><b>Function Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL__FUNCTION_PARAMETERS = eINSTANCE.getFunctionCall_FunctionParameters();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.PropertyRefImpl <em>Property Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.PropertyRefImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getPropertyRef()
     * @generated
     */
    EClass PROPERTY_REF = eINSTANCE.getPropertyRef();

    /**
     * The meta object literal for the '<em><b>Prop Access</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_REF__PROP_ACCESS = eINSTANCE.getPropertyRef_PropAccess();

    /**
     * The meta object literal for the '<em><b>Function Call</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_REF__FUNCTION_CALL = eINSTANCE.getPropertyRef_FunctionCall();

    /**
     * The meta object literal for the '<em><b>Collection Access</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_REF__COLLECTION_ACCESS = eINSTANCE.getPropertyRef_CollectionAccess();

    /**
     * The meta object literal for the '<em><b>List Func</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_REF__LIST_FUNC = eINSTANCE.getPropertyRef_ListFunc();

    /**
     * The meta object literal for the '<em><b>Sub Propery</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_REF__SUB_PROPERY = eINSTANCE.getPropertyRef_SubPropery();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.ConstantImpl <em>Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.ConstantImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getConstant()
     * @generated
     */
    EClass CONSTANT = eINSTANCE.getConstant();

    /**
     * The meta object literal for the '<em><b>Str Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__STR_VAL = eINSTANCE.getConstant_StrVal();

    /**
     * The meta object literal for the '<em><b>Int Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__INT_VAL = eINSTANCE.getConstant_IntVal();

    /**
     * The meta object literal for the '<em><b>Float Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__FLOAT_VAL = eINSTANCE.getConstant_FloatVal();

    /**
     * The meta object literal for the '<em><b>Bool Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__BOOL_VAL = eINSTANCE.getConstant_BoolVal();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.EntityImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.OrConditionImpl <em>Or Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.OrConditionImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getOrCondition()
     * @generated
     */
    EClass OR_CONDITION = eINSTANCE.getOrCondition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_CONDITION__LEFT = eINSTANCE.getOrCondition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_CONDITION__RIGHT = eINSTANCE.getOrCondition_Right();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.AndConditionImpl <em>And Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.AndConditionImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getAndCondition()
     * @generated
     */
    EClass AND_CONDITION = eINSTANCE.getAndCondition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_CONDITION__LEFT = eINSTANCE.getAndCondition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_CONDITION__RIGHT = eINSTANCE.getAndCondition_Right();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.impl.NegationImpl <em>Negation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.impl.NegationImpl
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getNegation()
     * @generated
     */
    EClass NEGATION = eINSTANCE.getNegation();

    /**
     * The meta object literal for the '<em><b>Negated</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEGATION__NEGATED = eINSTANCE.getNegation_Negated();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.Operator <em>Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.Operator
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getOperator()
     * @generated
     */
    EEnum OPERATOR = eINSTANCE.getOperator();

    /**
     * The meta object literal for the '{@link x.mvmn.permock.dsl.dsl.ListOperation <em>List Operation</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see x.mvmn.permock.dsl.dsl.ListOperation
     * @see x.mvmn.permock.dsl.dsl.impl.DslPackageImpl#getListOperation()
     * @generated
     */
    EEnum LIST_OPERATION = eINSTANCE.getListOperation();

  }

} //DslPackage
