/**
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Header</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link x.mvmn.permock.dsl.dsl.Header#getHeaderName <em>Header Name</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.Header#getHeaderValue <em>Header Value</em>}</li>
 * </ul>
 *
 * @see x.mvmn.permock.dsl.dsl.DslPackage#getHeader()
 * @model
 * @generated
 */
public interface Header extends EObject
{
  /**
   * Returns the value of the '<em><b>Header Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header Name</em>' attribute.
   * @see #setHeaderName(String)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getHeader_HeaderName()
   * @model
   * @generated
   */
  String getHeaderName();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.Header#getHeaderName <em>Header Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header Name</em>' attribute.
   * @see #getHeaderName()
   * @generated
   */
  void setHeaderName(String value);

  /**
   * Returns the value of the '<em><b>Header Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header Value</em>' attribute.
   * @see #setHeaderValue(String)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getHeader_HeaderValue()
   * @model
   * @generated
   */
  String getHeaderValue();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.Header#getHeaderValue <em>Header Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header Value</em>' attribute.
   * @see #getHeaderValue()
   * @generated
   */
  void setHeaderValue(String value);

} // Header
