/**
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link x.mvmn.permock.dsl.dsl.ListFunction#getOp <em>Op</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.ListFunction#getAlias <em>Alias</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.ListFunction#getSeparator <em>Separator</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.ListFunction#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see x.mvmn.permock.dsl.dsl.DslPackage#getListFunction()
 * @model
 * @generated
 */
public interface ListFunction extends EObject
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * The literals are from the enumeration {@link x.mvmn.permock.dsl.dsl.ListOperation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see x.mvmn.permock.dsl.dsl.ListOperation
   * @see #setOp(ListOperation)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getListFunction_Op()
   * @model
   * @generated
   */
  ListOperation getOp();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.ListFunction#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see x.mvmn.permock.dsl.dsl.ListOperation
   * @see #getOp()
   * @generated
   */
  void setOp(ListOperation value);

  /**
   * Returns the value of the '<em><b>Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' containment reference.
   * @see #setAlias(ListElementAlias)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getListFunction_Alias()
   * @model containment="true"
   * @generated
   */
  ListElementAlias getAlias();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.ListFunction#getAlias <em>Alias</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias</em>' containment reference.
   * @see #getAlias()
   * @generated
   */
  void setAlias(ListElementAlias value);

  /**
   * Returns the value of the '<em><b>Separator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Separator</em>' attribute.
   * @see #setSeparator(String)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getListFunction_Separator()
   * @model
   * @generated
   */
  String getSeparator();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.ListFunction#getSeparator <em>Separator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Separator</em>' attribute.
   * @see #getSeparator()
   * @generated
   */
  void setSeparator(String value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Condition)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getListFunction_Condition()
   * @model containment="true"
   * @generated
   */
  Condition getCondition();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.ListFunction#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Condition value);

} // ListFunction
