/**
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Negation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link x.mvmn.permock.dsl.dsl.Negation#getNegated <em>Negated</em>}</li>
 * </ul>
 *
 * @see x.mvmn.permock.dsl.dsl.DslPackage#getNegation()
 * @model
 * @generated
 */
public interface Negation extends Condition
{
  /**
   * Returns the value of the '<em><b>Negated</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Negated</em>' containment reference.
   * @see #setNegated(Condition)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getNegation_Negated()
   * @model containment="true"
   * @generated
   */
  Condition getNegated();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.Negation#getNegated <em>Negated</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Negated</em>' containment reference.
   * @see #getNegated()
   * @generated
   */
  void setNegated(Condition value);

} // Negation
