/**
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operand</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link x.mvmn.permock.dsl.dsl.Operand#getRef <em>Ref</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.Operand#getConst <em>Const</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.Operand#getListElementRef <em>List Element Ref</em>}</li>
 * </ul>
 *
 * @see x.mvmn.permock.dsl.dsl.DslPackage#getOperand()
 * @model
 * @generated
 */
public interface Operand extends EObject
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' containment reference.
   * @see #setRef(Reference)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getOperand_Ref()
   * @model containment="true"
   * @generated
   */
  Reference getRef();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.Operand#getRef <em>Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' containment reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Reference value);

  /**
   * Returns the value of the '<em><b>Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const</em>' containment reference.
   * @see #setConst(Constant)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getOperand_Const()
   * @model containment="true"
   * @generated
   */
  Constant getConst();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.Operand#getConst <em>Const</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const</em>' containment reference.
   * @see #getConst()
   * @generated
   */
  void setConst(Constant value);

  /**
   * Returns the value of the '<em><b>List Element Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Element Ref</em>' containment reference.
   * @see #setListElementRef(ListElementReference)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getOperand_ListElementRef()
   * @model containment="true"
   * @generated
   */
  ListElementReference getListElementRef();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.Operand#getListElementRef <em>List Element Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Element Ref</em>' containment reference.
   * @see #getListElementRef()
   * @generated
   */
  void setListElementRef(ListElementReference value);

} // Operand
