/**
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link x.mvmn.permock.dsl.dsl.PropertyRef#getPropAccess <em>Prop Access</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.PropertyRef#getFunctionCall <em>Function Call</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.PropertyRef#getCollectionAccess <em>Collection Access</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.PropertyRef#getListFunc <em>List Func</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.PropertyRef#getSubPropery <em>Sub Propery</em>}</li>
 * </ul>
 *
 * @see x.mvmn.permock.dsl.dsl.DslPackage#getPropertyRef()
 * @model
 * @generated
 */
public interface PropertyRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Prop Access</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prop Access</em>' containment reference.
   * @see #setPropAccess(PropertyAccess)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getPropertyRef_PropAccess()
   * @model containment="true"
   * @generated
   */
  PropertyAccess getPropAccess();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.PropertyRef#getPropAccess <em>Prop Access</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prop Access</em>' containment reference.
   * @see #getPropAccess()
   * @generated
   */
  void setPropAccess(PropertyAccess value);

  /**
   * Returns the value of the '<em><b>Function Call</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Call</em>' containment reference.
   * @see #setFunctionCall(FunctionCall)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getPropertyRef_FunctionCall()
   * @model containment="true"
   * @generated
   */
  FunctionCall getFunctionCall();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.PropertyRef#getFunctionCall <em>Function Call</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Call</em>' containment reference.
   * @see #getFunctionCall()
   * @generated
   */
  void setFunctionCall(FunctionCall value);

  /**
   * Returns the value of the '<em><b>Collection Access</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Collection Access</em>' containment reference.
   * @see #setCollectionAccess(CollectionAccess)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getPropertyRef_CollectionAccess()
   * @model containment="true"
   * @generated
   */
  CollectionAccess getCollectionAccess();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.PropertyRef#getCollectionAccess <em>Collection Access</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Collection Access</em>' containment reference.
   * @see #getCollectionAccess()
   * @generated
   */
  void setCollectionAccess(CollectionAccess value);

  /**
   * Returns the value of the '<em><b>List Func</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Func</em>' containment reference.
   * @see #setListFunc(ListFunction)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getPropertyRef_ListFunc()
   * @model containment="true"
   * @generated
   */
  ListFunction getListFunc();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.PropertyRef#getListFunc <em>List Func</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Func</em>' containment reference.
   * @see #getListFunc()
   * @generated
   */
  void setListFunc(ListFunction value);

  /**
   * Returns the value of the '<em><b>Sub Propery</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Propery</em>' containment reference.
   * @see #setSubPropery(PropertyRef)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getPropertyRef_SubPropery()
   * @model containment="true"
   * @generated
   */
  PropertyRef getSubPropery();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.PropertyRef#getSubPropery <em>Sub Propery</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Propery</em>' containment reference.
   * @see #getSubPropery()
   * @generated
   */
  void setSubPropery(PropertyRef value);

} // PropertyRef
