/**
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Response Conf</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link x.mvmn.permock.dsl.dsl.ResponseConf#getHttpStatus <em>Http Status</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.ResponseConf#getContent <em>Content</em>}</li>
 *   <li>{@link x.mvmn.permock.dsl.dsl.ResponseConf#getHeaders <em>Headers</em>}</li>
 * </ul>
 *
 * @see x.mvmn.permock.dsl.dsl.DslPackage#getResponseConf()
 * @model
 * @generated
 */
public interface ResponseConf extends EObject
{
  /**
   * Returns the value of the '<em><b>Http Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Http Status</em>' attribute.
   * @see #setHttpStatus(Long)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getResponseConf_HttpStatus()
   * @model
   * @generated
   */
  Long getHttpStatus();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.ResponseConf#getHttpStatus <em>Http Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Http Status</em>' attribute.
   * @see #getHttpStatus()
   * @generated
   */
  void setHttpStatus(Long value);

  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute.
   * @see #setContent(String)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getResponseConf_Content()
   * @model
   * @generated
   */
  String getContent();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.ResponseConf#getContent <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' attribute.
   * @see #getContent()
   * @generated
   */
  void setContent(String value);

  /**
   * Returns the value of the '<em><b>Headers</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Headers</em>' containment reference.
   * @see #setHeaders(Headers)
   * @see x.mvmn.permock.dsl.dsl.DslPackage#getResponseConf_Headers()
   * @model containment="true"
   * @generated
   */
  Headers getHeaders();

  /**
   * Sets the value of the '{@link x.mvmn.permock.dsl.dsl.ResponseConf#getHeaders <em>Headers</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Headers</em>' containment reference.
   * @see #getHeaders()
   * @generated
   */
  void setHeaders(Headers value);

} // ResponseConf
