/*
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DslStandaloneSetup extends DslStandaloneSetupGenerated {

	public static void doSetup() {
		new DslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
