/*
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import x.mvmn.permock.dsl.DslRuntimeModule;
import x.mvmn.permock.dsl.DslStandaloneSetup;
import x.mvmn.permock.dsl.ide.DslIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class DslWebSetup extends DslStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DslRuntimeModule(), new DslIdeModule(), new DslWebModule()));
	}
	
}
