/*
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link DslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractDslWebModule extends DefaultWebModule {

}
