/*
 * generated by Xtext 2.25.0
 */
package x.mvmn.permock.dsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class DslWebModule extends AbstractDslWebModule {
}
